apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-movie-deployment
  namespace: rampup-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-movie-label
  template:
    metadata:
      labels:
        app: backend-movie-label
    spec:
      containers:
      - image: 419466290453.dkr.ecr.sa-east-1.amazonaws.com/rampup-backend:latest
        imagePullPolicy: Always
        name: backend-movie-container
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_entrypoint
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_pass
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db_name
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: bk_port
        ports:
        - containerPort: 3000
          name: backend-port
---
apiVersion: v1
kind: Service
metadata:
    name: backend-svc
    namespace: rampup-ns
spec:
    ports:
    - port: 3000
    selector:
        app: backend-movie-label
    type: ClusterIP
---