apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: frontend_movie
  name: frontend_movie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fontend_movie
  template:
    metadata:
      labels:
        app: frontend_movie
    spec:
      containers:
      - image: 419466290453.dkr.ecr.sa-east-1.amazonaws.com/rampup-frontend:latest
        imagePullPolicy: Always
        name: frontend_movie
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: frontend_movie
    name: frontend_svc
spec:
    ports:
    - port: 3030
      protocol: TCP
      targetPort: 3030
    selector:
        app: frontend_movie
    type: ClusterIP