apiVersion: v1
kind: namespace
metadata:
  name: rampup-frontend-ns

apiVersion: app/v1
kind: Deployment
metadata:
  name: frontend-movie-deployment
  namespace: rampup-frontend-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-movie-lable
  template:
    metadata:
      labels:
        app: frontend-movie-lable
    spec:
      containers:
      - image: 419466290453.dkr.ecr.sa-east-1.amazonaws.com/rampup-frontend:latest
        imagePullPolicy: Always
        name: frontend-movie-container
        port:
        - containerPort: 3030
          name: frontend-port
          targetPort: 3030
---
apiVersion: v1
kind: Service
metadata:
    name: frontend-svc
    namespace: rampup-frontend-ns
spec:
    ports:
    - port: 3030
    selector:
        app: frontend-movie
    type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metada:
  name: frontend-ingress
  namespace: rampup-frontend-ns
spec:
  rules:
    - host: app.movie-ui.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend-svc
              port:
                - number: 3030