{
 "title": "Rampup Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage inc",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (cpu)(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))*100)"
    }
   ]
  },
  {
   "title": "Open TCP connections rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_ActiveOpens{}[1m])*100"
    }
   ]
  },
  {
   "title": "Mem_in_use%",
   "type": "gauge",
   "description": "Percentage of mem in use",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_Active_bytes/node_memory_MemTotal_bytes*100"
    }
   ]
  }
 ]
}