{
 "title": "Rampup Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Worker nodes info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hardware usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (cpu)(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])))",
     "legendFormat": "Rate of CPU Usage"
    },
    {
     "expr": "node_memory_Active_bytes/node_memory_MemTotal_bytes*100",
     "legendFormat": "Free Mem"
    }
   ]
  },
  { "title": "Frontend info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Percentage of 404 responses (5m)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(delta(nginx_ingress_controller_requests{service=\"frontend-svc\", status=\"404\", job=\"ingress-nginx-endpoints\"}[5m])) / sum(delta(nginx_ingress_controller_requests{service=\"frontend-svc\", job=\"ingress-nginx-endpoints\"}[5m])))*100",
     "legendFormat": "404 status %"
    }
   ]
  },
  {
   "title": "Response type division (last hour)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status)(delta(nginx_ingress_controller_requests{service=\"frontend-svc\", job=\"ingress-nginx-endpoints\"}[1h]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}