    //environment{
    //    db_port=credentials('db_port')
    //    db_entrypoint=credentials('db_entrypoint')
    //    db_user=credentials('db_user')
    //    db_pass=credentials('db_pass')
    //    db_name=credentials('db_name')
    //    backend_port=credentials('backend_port')
    //}
pipeline{
    agent any
    stages{
        stage('GitCheckout & deploy infra') {
            steps{
                checkout scm
                script{
                    sh 'knife cookbook upload -a'
                    sh 'knife role from file "./../../chef-repo/worker-role-template.json"'
                    sh 'knife role from file "./../../chef-repo/master-role-template.json"'
                    sh 'cd ./tf-setup-services'
                    withCredentials([aws(credentialsId: 'aws_credentials', accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                        sh 'terraform init'
                        sh 'terraform apply -auto-approve'
                        master_node_ip  = sh(
                            script: "aws ec2 describe-instances --filter Name=instance.group-name,Values=master-node-sg --query 'Reservations[*].Instances[*].PrivateIpAddress' --output text",
                            returnStdout: true)
                        worker_node_ip  = sh(
                            script: "aws ec2 describe-instances --filter Name=instance.group-name,Values=worker-node-sg --query 'Reservations[*].Instances[*].PrivateIpAddress' --output text",
                            returnStdout: true)
                    }
                    withCredentials([file(credentialsId:'ssh_keypair', variable:'ssh_key')]){
                        sh "knife bootstrap $master_node_ip -U ec2-user --sudo -i $ssh_key -N master-node -r 'role[master]'"
                        sh "knife bootstrap $worker_node_ip -U ec2-user --sudo -i $ssh_key -N worker-node -r 'role[worker]'"
                        join_command  = sh(
                            script: "ssh -i $ssh_key ec2-user@$master_node_ip kubeadm token create --print-join-command --ttl 1m",
                            returnStdout: true)
                        sh "ssh -i $ssh_key ec2-user@$worker_node_ip sudo $join_command"
                        sh "ssh -i $ssh_key ec2-user@$worker_node_ip sudo kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml"
                        sh "ssh -i $ssh_key ec2-user@$worker_node_ip sudo kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/baremetal/1.23/deploy.yaml"
                    }
                }
            }
        }
    }
}
